'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {ArrowLeft,CheckCircle2,PackageCheck} from 'lucide-react';
import {useParams} from 'next/navigation';
import {createClient} from '@/lib/supabase/client';
type Batch={id:string;competence:string;production_type:string;status:string;record_count:number;created_at:string;exported_at:string|null};
type Item={id:string;production_date:string;quantity:number;status:string;patient:{name:string}|null;procedure:{code:string;name:string}|null};
export default function LoteDetalhe(){const{id}=useParams<{id:string}>();const supabase=createClient();const[batch,setBatch]=useState<Batch|null>(null),[items,setItems]=useState<Item[]>([]),[message,setMessage]=useState(''),[saving,setSaving]=useState(false);
async function load(){const[b,p]=await Promise.all([supabase.from('sus_export_batches').select('id,competence,production_type,status,record_count,created_at,exported_at').eq('id',id).single(),supabase.from('sus_production').select('id,production_date,quantity,status,patient:patients(name),procedure:sigtap_procedures(code,name)').eq('export_batch_id',id).order('production_date')]);if(b.error)setMessage('Lote não encontrado ou sem permissão de acesso.');else setBatch(b.data as Batch);if(!p.error)setItems((p.data??[]) as unknown as Item[])}
useEffect(()=>{if(id)load()},[id]);
async function closeBatch(){if(!batch||batch.status!=='OPEN'||!items.length)return;if(!window.confirm('Fechar este lote? Após o fechamento ele ficará marcado como exportado.'))return;setSaving(true);setMessage('');const now=new Date().toISOString();const{error:prodError}=await supabase.from('sus_production').update({status:'EXPORTED',exported_at:now,export_batch:batch.id,updated_at:now}).eq('export_batch_id',batch.id).eq('status','VALIDATED');if(prodError){setMessage('Não foi possível fechar as produções: '+prodError.message);setSaving(false);return}const{error}=await supabase.from('sus_export_batches').update({status:'EXPORTED',record_count:items.length,exported_at:now}).eq('id',batch.id).eq('status','OPEN');if(error){setMessage('As produções foram atualizadas, mas o lote não pôde ser fechado: '+error.message);setSaving(false);return}setMessage('Lote fechado. Os registros foram marcados como exportados.');setSaving(false);await load()}
return <main className="min-h-screen p-4 md:p-8"><div className="mx-auto max-w-6xl"><div className="mb-6 flex items-center justify-between gap-4"><div><h1 className="text-2xl font-bold tracking-tight text-slate-950 lg:text-3xl">Detalhes do lote</h1><p className="text-sm text-slate-500">{batch?batch.production_type+' • competência '+batch.competence:'Carregando...'}</p></div><Link href="/producao/lotes" className="flex items-center gap-2 rounded-lg border bg-white px-3 py-2 text-sm"><ArrowLeft size={16}/> Lotes</Link></div>{message&&<div className="mb-4 rounded-lg border bg-white p-3 text-sm">{message}</div>}{batch&&<div className="mb-5 flex flex-wrap items-center justify-between gap-3 rounded-xl border bg-white p-4"><div><b>{batch.status==='OPEN'?'Lote aberto':batch.status==='EXPORTED'?'Lote exportado':'Lote cancelado'}</b><div className="text-xs text-slate-500">{items.length} registro(s) vinculado(s)</div></div>{batch.status==='OPEN'&&<button disabled={saving||!items.length} onClick={closeBatch} className="flex items-center gap-2 rounded-lg bg-slate-900 px-4 py-2 text-sm font-medium text-white disabled:opacity-50"><CheckCircle2 size={16}/>{saving?'Fechando...':'Fechar lote'}</button>}</div>}<section className="overflow-hidden rounded-xl border bg-white">{items.length===0?<div className="p-8 text-center text-sm text-slate-500">Nenhum registro vinculado ao lote.</div>:<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-3">Data</th><th className="p-3">Paciente</th><th className="p-3">Procedimento</th><th className="p-3">Qtd.</th><th className="p-3">Status</th></tr></thead><tbody className="divide-y">{items.map(x=><tr key={x.id}><td className="p-3">{x.production_date}</td><td className="p-3 font-medium">{x.patient?.name??'—'}</td><td className="p-3">{x.procedure?.code??'—'} — {x.procedure?.name??'Procedimento não encontrado'}</td><td className="p-3">{x.quantity}</td><td className="p-3">{x.status}</td></tr>)}</tbody></table></div>}</section>{batch?.status==='EXPORTED'&&<div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">O lote está fechado no sistema. A geração do arquivo oficial BPA/SIA-SUS ainda não está habilitada; o fechamento não significa validação pelo sistema oficial do SUS.</div>}</div></main>}