'use client';
import {ChangeEvent,useState} from 'react';
import Link from 'next/link';
import {FileSpreadsheet,Upload} from 'lucide-react';
import * as XLSX from 'xlsx';
import {createClient} from '@/lib/supabase/client';
type Row={line:number;code:string;name:string;complexity:string;financing:string;competence:string;valid:boolean;error?:string};
const norm=(s:string)=>s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');
function rowsFromSheet(sheet:XLSX.WorkSheet):Row[]{const raw=XLSX.utils.sheet_to_json<Record<string,unknown>>(sheet,{defval:''});return raw.map((x,i)=>{const m=new Map(Object.entries(x).map(([k,v])=>[norm(k),String(v).trim()]));const get=(...ks:string[])=>ks.map(norm).map(k=>m.get(k)).find(Boolean)||'';const code=get('codigo','cod_procedimento','codigo_procedimento','co_procedimento').replace(/\D/g,'');const name=get('nome','procedimento','nome_procedimento','no_procedimento');const competence=get('competencia','competência','dt_competencia');const error=!code?'Código ausente':code.length!==10?'Código deve ter 10 dígitos':!name?'Nome ausente':'';return{line:i+2,code,name,complexity:get('complexidade','complexity'),financing:get('financiamento','forma_financiamento','financing'),competence,valid:!error,error:error||undefined}})}
export default function ImportSigtap(){const supabase=createClient();const[rows,setRows]=useState<Row[]>([]),[fileName,setFileName]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
async function choose(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;setFileName(f.name);setMessage('');try{const book=XLSX.read(await f.arrayBuffer(),{type:'array'});const sheet=book.Sheets[book.SheetNames[0]];setRows(rowsFromSheet(sheet))}catch{setMessage('Não foi possível ler o arquivo. Use CSV, XLSX ou XLS com cabeçalhos de procedimento.')}}
async function confirm(){const ready=rows.filter(r=>r.valid);if(!ready.length)return;setBusy(true);const payload=ready.map(r=>({code:r.code,name:r.name,complexity:r.complexity||null,financing:r.financing||null,competence:r.competence||null,active:true,updated_at:new Date().toISOString()}));const{error}=await supabase.from('sigtap_procedures').upsert(payload,{onConflict:'code'});setBusy(false);if(error){setMessage('Importação não concluída: '+error.message);return}setMessage(`${ready.length} procedimento(s) processado(s) com sucesso a partir de ${fileName}.`);setRows([])}
const ok=rows.filter(x=>x.valid).length,bad=rows.length-ok;return <main className="min-h-screen bg-slate-50"><header className="border-b bg-white px-6 py-5"><div className="flex items-center gap-2 text-sm text-slate-500"><FileSpreadsheet size={16}/> SIGTAP</div><h1 className="mt-1 text-2xl font-bold">Importar procedimentos</h1><p className="mt-1 text-sm text-slate-500">Carga por arquivo com prévia antes de atualizar o catálogo.</p></header><div className="p-6">{message&&<div className="mb-4 rounded-lg border bg-white p-3 text-sm">{message}</div>}<label className="flex cursor-pointer items-center justify-center gap-2 rounded-xl border-2 border-dashed bg-white p-8 text-sm font-medium"><Upload size={20}/> Selecionar CSV ou Excel<input type="file" accept=".csv,.xlsx,.xls" className="hidden" onChange={choose}/></label><p className="mt-2 text-xs text-slate-500">O importador procura código do procedimento, nome e, quando disponíveis, complexidade, financiamento e competência. Nenhum dado é gravado antes da confirmação.</p>{rows.length>0&&<><div className="my-4 grid gap-3 sm:grid-cols-3"><Stat label="Linhas" value={rows.length}/><Stat label="Válidas" value={ok}/><Stat label="Com erro" value={bad}/></div><div className="max-h-[420px] overflow-auto rounded-xl border bg-white"><table className="w-full text-sm"><thead className="sticky top-0 bg-slate-50 text-left"><tr><th className="p-3">Linha</th><th>Código</th><th>Procedimento</th><th>Competência</th><th>Situação</th></tr></thead><tbody>{rows.slice(0,500).map(r=><tr key={r.line} className="border-t"><td className="p-3">{r.line}</td><td>{r.code||'—'}</td><td>{r.name||'—'}</td><td>{r.competence||'—'}</td><td className={r.valid?'text-emerald-700':'text-red-700'}>{r.valid?'Pronto':r.error}</td></tr>)}</tbody></table></div><div className="mt-4 flex justify-end gap-2"><Link href="/producao" className="rounded-lg border px-4 py-2 text-sm">Voltar</Link><button onClick={confirm} disabled={busy||ok===0} className="rounded-lg bg-slate-900 px-4 py-2 text-sm text-white disabled:opacity-50">{busy?'Importando...':`Processar ${ok} procedimento(s)`}</button></div></>}</div></main>}
function Stat({label,value}:{label:string;value:number}){return <div className="rounded-xl border bg-white p-4"><div className="text-xs text-slate-500">{label}</div><div className="text-2xl font-bold">{value}</div></div>}