'use client';
import {FormEvent,useEffect,useState} from 'react';
import Link from 'next/link';
import {ArrowLeft,PackageCheck} from 'lucide-react';
import {createClient} from '@/lib/supabase/client';
type Batch={id:string;competence:string;production_type:string;status:string;record_count:number;created_at:string;exported_at:string|null};
export default function LotesPage(){const supabase=createClient();const[rows,setRows]=useState<Batch[]>([]),[message,setMessage]=useState(''),[saving,setSaving]=useState(false);
async function load(){const{data,error}=await supabase.from('sus_export_batches').select('id,competence,production_type,status,record_count,created_at,exported_at').order('created_at',{ascending:false}).limit(100);if(error)setMessage('Não foi possível carregar os lotes: '+error.message);else setRows((data??[]) as Batch[])}
useEffect(()=>{load()},[]);
async function createBatch(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setMessage('');const fd=new FormData(e.currentTarget),competence=String(fd.get('competence')??'').replace(/\D/g,''),type=String(fd.get('production_type')??'');if(!/^\d{6}$/.test(competence)){setMessage('Informe a competência no formato AAAAMM.');setSaving(false);return}const{data:{user}}=await supabase.auth.getUser();if(!user){setMessage('Sessão expirada.');setSaving(false);return}const{data:profile}=await supabase.from('profiles').select('municipality_id').eq('id',user.id).single();if(!profile?.municipality_id){setMessage('Prefeitura não identificada.');setSaving(false);return}const start=competence.slice(0,4)+'-'+competence.slice(4,6)+'-01';const nextMonth=new Date(Number(competence.slice(0,4)),Number(competence.slice(4,6)),1).toISOString().slice(0,10);const{data:production,error:prodError}=await supabase.from('sus_production').select('id').eq('municipality_id',profile.municipality_id).eq('production_type',type).eq('status','VALIDATED').is('export_batch_id',null).gte('production_date',start).lt('production_date',nextMonth);if(prodError){setMessage(prodError.message);setSaving(false);return}if(!production?.length){setMessage('Nenhuma produção validada e disponível para esta competência e tipo.');setSaving(false);return}const{data:batch,error}=await supabase.from('sus_export_batches').insert({municipality_id:profile.municipality_id,competence,production_type:type,status:'OPEN',record_count:production.length,created_by:user.id}).select('id').single();if(error||!batch){setMessage('Não foi possível criar o lote: '+(error?.message??'erro desconhecido'));setSaving(false);return}const ids=production.map(x=>x.id);const{error:linkError}=await supabase.from('sus_production').update({export_batch_id:batch.id}).in('id',ids);if(linkError){await supabase.from('sus_export_batches').delete().eq('id',batch.id);setMessage('Não foi possível vincular as produções ao lote: '+linkError.message);setSaving(false);return}(e.currentTarget).reset();setMessage('Lote criado com '+production.length+' registro(s) validado(s).');setSaving(false);await load()}
return <main className="min-h-screen bg-slate-50 p-4 md:p-8"><div className="mx-auto max-w-6xl"><div className="mb-6 flex items-center justify-between gap-4"><div><div className="flex items-center gap-2 text-sm text-slate-500"><PackageCheck size={16}/> SUS</div><h1 className="text-2xl font-bold">Lotes BPA / TFD</h1><p className="text-sm text-slate-500">Agrupe produções já validadas por competência e tipo.</p></div><Link href="/producao" className="flex items-center gap-2 rounded-lg border bg-white px-3 py-2 text-sm"><ArrowLeft size={16}/> Produção</Link></div>{message&&<div className="mb-4 rounded-lg border bg-white p-3 text-sm">{message}</div>}<form onSubmit={createBatch} className="mb-6 grid gap-3 rounded-xl border bg-white p-5 md:grid-cols-3"><input name="competence" inputMode="numeric" maxLength={6} placeholder="Competência AAAAMM" required className="rounded-lg border p-2 text-sm"/><select name="production_type" className="rounded-lg border p-2 text-sm"><option value="BPA_I">BPA-I</option><option value="BPA_C">BPA-C</option><option value="TFD">TFD</option></select><button disabled={saving} className="rounded-lg bg-slate-900 px-3 py-2 text-sm font-medium text-white disabled:opacity-50">{saving?'Criando lote...':'Criar lote com produções validadas'}</button></form><section className="overflow-hidden rounded-xl border bg-white">{rows.length===0?<div className="p-8 text-center text-sm text-slate-500">Nenhum lote criado.</div>:<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-3">Competência</th><th className="p-3">Tipo</th><th className="p-3">Registros</th><th className="p-3">Status</th><th className="p-3">Criado em</th></tr></thead><tbody className="divide-y">{rows.map(r=><tr key={r.id}><td className="p-3 font-medium">{r.competence.slice(0,4)+'/'+r.competence.slice(4)}</td><td className="p-3">{r.production_type}</td><td className="p-3">{r.record_count}</td><td className="p-3">{r.status==='OPEN'?'Aberto':r.status==='EXPORTED'?'Exportado':'Cancelado'}</td><td className="p-3">{new Date(r.created_at).toLocaleString('pt-BR')}</td></tr>)}</tbody></table></div>}</section></div></main>}