'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {ArrowLeft,FileSpreadsheet} from 'lucide-react';
import {createClient} from '@/lib/supabase/client';
type Batch={id:string;file_name:string;source:string;total_rows:number;imported_rows:number;duplicate_rows:number;error_rows:number;status:'PREVIEW'|'COMPLETED'|'FAILED';created_at:string;completed_at:string|null;created_by:string|null};
type Profile={id:string;name:string};
const statusLabel={PREVIEW:'Em preparação',COMPLETED:'Concluído',FAILED:'Falhou'};
export default function HistoricoImportacoes(){const supabase=createClient();const[rows,setRows]=useState<Batch[]>([]),[names,setNames]=useState<Record<string,string>>({}),[status,setStatus]=useState(''),[loading,setLoading]=useState(true),[message,setMessage]=useState('');
useEffect(()=>{(async()=>{setLoading(true);const{data,error}=await supabase.from('patient_import_batches').select('id,file_name,source,total_rows,imported_rows,duplicate_rows,error_rows,status,created_at,completed_at,created_by').order('created_at',{ascending:false}).limit(200);if(error){setMessage('Não foi possível carregar o histórico: '+error.message);setLoading(false);return}const batches=(data??[]) as Batch[];setRows(batches);const ids=[...new Set(batches.map(x=>x.created_by).filter(Boolean))] as string[];if(ids.length){const{data:p}=await supabase.from('profiles').select('id,name').in('id',ids);setNames(Object.fromEntries(((p??[]) as Profile[]).map(x=>[x.id,x.name])))}setLoading(false)})();},[]);
const filtered=status?rows.filter(r=>r.status===status):rows;
return <main className="min-h-screen bg-slate-50 p-4 md:p-8"><div className="mx-auto max-w-6xl"><div className="mb-6 flex items-center justify-between gap-4"><div><div className="flex items-center gap-2 text-sm text-slate-500"><FileSpreadsheet size={16}/> Integrações</div><h1 className="text-2xl font-bold">Histórico de importações</h1><p className="text-sm text-slate-500">Lotes de pacientes importados por arquivo.</p></div><Link href="/pacientes/importar" className="flex items-center gap-2 rounded-lg border bg-white px-3 py-2 text-sm"><ArrowLeft size={16}/> Importar pacientes</Link></div>
<div className="mb-4 max-w-xs"><select value={status} onChange={e=>setStatus(e.target.value)} className="w-full rounded-lg border bg-white px-3 py-2 text-sm"><option value="">Todos os status</option><option value="COMPLETED">Concluídos</option><option value="FAILED">Falhas</option><option value="PREVIEW">Em preparação</option></select></div>
{message&&<div className="mb-4 rounded-lg border bg-white p-3 text-sm">{message}</div>}<section className="overflow-hidden rounded-xl border bg-white shadow-sm">{loading?<div className="p-6 text-sm text-slate-500">Carregando...</div>:filtered.length===0?<div className="p-6 text-sm text-slate-500">Nenhuma importação registrada.</div>:<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-3">Data</th><th className="p-3">Arquivo</th><th className="p-3">Responsável</th><th className="p-3">Status</th><th className="p-3">Total</th><th className="p-3">Importados</th><th className="p-3">Duplicados</th><th className="p-3">Erros</th></tr></thead><tbody className="divide-y">{filtered.map(r=><tr key={r.id}><td className="whitespace-nowrap p-3">{new Date(r.created_at).toLocaleString('pt-BR')}</td><td className="p-3 font-medium">{r.file_name}</td><td className="p-3">{r.created_by?names[r.created_by]??'Usuário':'—'}</td><td className="p-3">{statusLabel[r.status]}</td><td className="p-3">{r.total_rows}</td><td className="p-3">{r.imported_rows}</td><td className="p-3">{r.duplicate_rows}</td><td className="p-3">{r.error_rows}</td></tr>)}</tbody></table></div>}</section></div></main>}