'use client';
import {ChangeEvent,useState} from 'react';
import Link from 'next/link';
import {FileSpreadsheet,Upload,CheckCircle2,AlertTriangle} from 'lucide-react';
import {createClient} from '@/lib/supabase/client';
import * as XLSX from 'xlsx';

type Row={line:number;name:string;cpf:string;cns:string;birth_date:string;phone:string;city:string;valid:boolean;errors:string[];duplicate?:string};
const digits=(v:string)=>v.replace(/\D/g,'');
function cpfOk(v:string){if(!/^\d{11}$/.test(v)||/^(\d)\1{10}$/.test(v))return false;let s=0;for(let i=0;i<9;i++)s+=+v[i]*(10-i);let d=s*10%11;if(d===10)d=0;if(d!==+v[9])return false;s=0;for(let i=0;i<10;i++)s+=+v[i]*(11-i);d=s*10%11;if(d===10)d=0;return d===+v[10]}
function cnsOk(v:string){if(!/^\d{15}$/.test(v)||/^0{15}$/.test(v))return false;let s=0;for(let i=0;i<15;i++)s+=+v[i]*(15-i);return s%11===0}
function parseCsv(text:string){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean);if(!lines.length)return [];const sep=(lines[0].match(/;/g)||[]).length>(lines[0].match(/,/g)||[]).length?';':',';const parse=(line:string)=>{const out:string[]=[];let cur='',q=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if(ch===sep&&!q){out.push(cur.trim());cur=''}else cur+=ch}out.push(cur.trim());return out};const h=parse(lines[0]).map(x=>x.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,'_'));return lines.slice(1).map((l,i)=>{const v=parse(l),get=(...names:string[])=>{const ix=h.findIndex(x=>names.includes(x));return ix>=0?v[ix]??'':''};const name=get('nome','name','nome_completo'),cpf=digits(get('cpf')),cns=digits(get('cns','cartao_sus')),birth_date=get('data_nascimento','nascimento','birth_date'),phone=digits(get('telefone','phone','celular')),city=get('cidade','municipio','city');const errors:string[]=[];if(!name)errors.push('Nome obrigatório');if(cpf&&!cpfOk(cpf))errors.push('CPF inválido');if(cns&&!cnsOk(cns))errors.push('CNS inválido');return{line:i+2,name,cpf,cns,birth_date,phone,city,valid:errors.length===0,errors} as Row})}

export default function ImportPatientsPage(){const supabase=createClient();const[rows,setRows]=useState<Row[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[fileName,setFileName]=useState('');
async function fileChange(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setMessage('');setFileName(file.name);let parsed:Row[]=[];const lower=file.name.toLowerCase();if(lower.endsWith('.csv')){parsed=parseCsv(await file.text())}else if(lower.endsWith('.xlsx')||lower.endsWith('.xls')){try{const book=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:false});const sheet=book.Sheets[book.SheetNames[0]];const csv=XLSX.utils.sheet_to_csv(sheet,{FS:';'});parsed=parseCsv(csv)}catch{setMessage('Não foi possível ler a planilha Excel. Confira o arquivo e tente novamente.');return}}else{setMessage('Formato não suportado. Envie CSV, XLSX ou XLS.');return}if(!parsed.length){setMessage('O arquivo não possui registros para importar.');return}const cpfs=parsed.map(r=>r.cpf).filter(Boolean),cnss=parsed.map(r=>r.cns).filter(Boolean);let existing:{id:string;name:string;cpf:string|null;cns:string|null}[]=[];if(cpfs.length){const{data}=await supabase.from('patients').select('id,name,cpf,cns').in('cpf',cpfs);existing.push(...((data??[]) as typeof existing))}if(cnss.length){const{data}=await supabase.from('patients').select('id,name,cpf,cns').in('cns',cnss);existing.push(...((data??[]) as typeof existing))}setRows(parsed.map(r=>{const d=existing.find(x=>(r.cpf&&x.cpf===r.cpf)||(r.cns&&x.cns===r.cns));return{...r,duplicate:d?.name}}));}
async function confirm(){const ready=rows.filter(r=>r.valid&&!r.duplicate);if(!ready.length)return;setBusy(true);const {data:{user}}=await supabase.auth.getUser();const {data:profile}=user?await supabase.from('profiles').select('municipality_id').eq('id',user.id).single():{data:null};if(!profile?.municipality_id){setBusy(false);setMessage('Não foi possível identificar a prefeitura para registrar a importação.');return}const {data:batch}=await supabase.from('patient_import_batches').insert({municipality_id:profile.municipality_id,created_by:user?.id??null,file_name:fileName||'arquivo',source:'FILE',total_rows:rows.length,duplicate_rows:rows.filter(r=>r.duplicate).length,error_rows:rows.filter(r=>!r.valid).length,status:'PREVIEW'}).select('id').single();const payload=ready.map(r=>({name:r.name,cpf:r.cpf||null,cns:r.cns||null,birth_date:r.birth_date||null,phone:r.phone||null,city:r.city||null}));const{error}=await supabase.from('patients').insert(payload);if(error){if(batch?.id)await supabase.from('patient_import_batches').update({status:'FAILED'}).eq('id',batch.id);setBusy(false);setMessage('Importação não concluída: '+error.message);return}if(batch?.id)await supabase.from('patient_import_batches').update({status:'COMPLETED',imported_rows:ready.length,completed_at:new Date().toISOString()}).eq('id',batch.id);setBusy(false);setMessage(`${ready.length} paciente(s) importado(s) com sucesso. O lote foi registrado no histórico.`);setRows([])}
const ok=rows.filter(r=>r.valid&&!r.duplicate).length,dup=rows.filter(r=>r.duplicate).length,bad=rows.filter(r=>!r.valid).length;
return <main className="min-h-screen bg-slate-50"><header className="border-b bg-white px-6 py-5"><div className="flex items-center gap-2 text-sm text-slate-500"><FileSpreadsheet size={16}/> Integrações</div><h1 className="mt-1 text-2xl font-bold">Importar pacientes</h1><p className="mt-1 text-sm text-slate-500">Pré-visualize, valide CPF/CNS e evite duplicidades antes de gravar.</p></header><div className="p-6">{message&&<div className="mb-4 rounded-lg border bg-white p-3 text-sm">{message}</div>}<div className="rounded-xl border bg-white p-6"><label className="flex cursor-pointer items-center justify-center gap-2 rounded-xl border-2 border-dashed p-8 text-sm font-medium"><Upload size={20}/> Selecionar CSV ou Excel<input type="file" accept=".csv,.xlsx,.xls,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel" className="hidden" onChange={fileChange}/></label><p className="mt-3 text-xs text-slate-500">Formatos aceitos: CSV, XLSX e XLS. Cabeçalhos reconhecidos: nome, CPF, CNS/cartão SUS, data_nascimento, telefone e cidade/município. O arquivo só é gravado após sua confirmação.</p></div>{rows.length>0&&<><div className="my-5 grid gap-3 sm:grid-cols-3"><Stat label="Prontos para importar" value={ok}/><Stat label="Duplicados" value={dup}/><Stat label="Com erro" value={bad}/></div><div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="p-3">Linha</th><th>Paciente</th><th>CPF</th><th>CNS</th><th>Situação</th></tr></thead><tbody>{rows.map(r=><tr key={r.line} className="border-t"><td className="p-3">{r.line}</td><td>{r.name||'—'}</td><td>{r.cpf||'—'}</td><td>{r.cns||'—'}</td><td className="pr-3">{r.duplicate?<span className="text-amber-700"><AlertTriangle className="inline" size={14}/> Já cadastrado: {r.duplicate}</span>:r.valid?<span className="text-emerald-700"><CheckCircle2 className="inline" size={14}/> Pronto</span>:<span className="text-red-700">{r.errors.join(', ')}</span>}</td></tr>)}</tbody></table></div><div className="mt-4 flex justify-end gap-2"><Link href="/pacientes" className="rounded-lg border px-4 py-2 text-sm">Cancelar</Link><button disabled={busy||ok===0} onClick={confirm} className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-medium text-white disabled:opacity-50">{busy?'Importando...':`Importar ${ok} paciente(s)`}</button></div></>}</div></main>}
function Stat({label,value}:{label:string;value:number}){return <div className="rounded-xl border bg-white p-4"><div className="text-xs text-slate-500">{label}</div><div className="mt-1 text-2xl font-bold">{value}</div></div>}