-- LGPD: minimiza snapshots de auditoria, evitando duplicar dados pessoais e textos livres.
create or replace function private.audit_snapshot_patient(p public.patients) returns jsonb language sql immutable set search_path='' as $$ select jsonb_build_object('id',p.id,'active',p.active,'wheelchair',p.wheelchair,'reduced_mobility',p.reduced_mobility,'stretcher',p.stretcher,'needs_companion',p.needs_companion,'municipality_id',p.municipality_id) $$;
create or replace function private.audit_snapshot_request(r public.transport_requests) returns jsonb language sql immutable set search_path='' as $$ select jsonb_build_object('id',r.id,'patient_id',r.patient_id,'date',r.date,'time',r.time,'health_unit_id',r.health_unit_id,'needs_companion',r.needs_companion,'status',r.status,'approved_by',r.approved_by,'approved_at',r.approved_at,'cancelled_at',r.cancelled_at,'cancelled_by',r.cancelled_by,'denied_at',r.denied_at,'denied_by',r.denied_by,'financing_distance_km',r.financing_distance_km,'municipality_id',r.municipality_id) $$;
create or replace function private.audit_snapshot_trip(t public.trips) returns jsonb language sql immutable set search_path='' as $$ select jsonb_build_object('id',t.id,'date',t.date,'departure_time',t.departure_time,'driver_id',t.driver_id,'vehicle_id',t.vehicle_id,'initial_mileage',t.initial_mileage,'final_mileage',t.final_mileage,'status',t.status,'operational_status',t.operational_status,'started_at',t.started_at,'completed_at',t.completed_at,'cancelled_at',t.cancelled_at,'route_distance_km',t.route_distance_km,'municipality_id',t.municipality_id) $$;
create or replace function private.audit_snapshot_occurrence(o public.occurrences) returns jsonb language sql immutable set search_path='' as $$ select jsonb_build_object('id',o.id,'vehicle_id',o.vehicle_id,'trip_id',o.trip_id,'date',o.date,'type',o.type,'status',o.status,'driver_id',o.driver_id,'patient_id',o.patient_id,'resolved_at',o.resolved_at,'resolved_by',o.resolved_by,'municipality_id',o.municipality_id) $$;
revoke execute on function private.audit_snapshot_patient(public.patients) from public,anon,authenticated;
revoke execute on function private.audit_snapshot_request(public.transport_requests) from public,anon,authenticated;
revoke execute on function private.audit_snapshot_trip(public.trips) from public,anon,authenticated;
revoke execute on function private.audit_snapshot_occurrence(public.occurrences) from public,anon,authenticated;

create or replace function private.record_patient_history() returns trigger language plpgsql security definer set search_path='' as $$
declare current_user_id uuid := (select auth.uid()); current_municipality uuid := coalesce(new.municipality_id,old.municipality_id); action_name text;
begin if tg_op='INSERT' then action_name:='CREATED'; elsif tg_op='UPDATE' then if old.active=true and new.active=false then action_name:='DEACTIVATED'; elsif old.active=false and new.active=true then action_name:='REACTIVATED'; else action_name:='UPDATED'; end if; else action_name:='UPDATED'; end if;
insert into public.patient_history(patient_id,municipality_id,user_id,action,old_data,new_data) values(coalesce(new.id,old.id),current_municipality,current_user_id,action_name,case when tg_op in ('UPDATE','DELETE') then private.audit_snapshot_patient(old) end,case when tg_op in ('INSERT','UPDATE') then private.audit_snapshot_patient(new) end); return coalesce(new,old); end $$;

create or replace function private.record_transport_request_history() returns trigger language plpgsql security definer set search_path='' as $$
declare a text;n text; begin if tg_op='INSERT' then a:='CREATED'; elsif new.status is distinct from old.status then a:='STATUS_CHANGED'; else a:='UPDATED'; end if; if new.status in ('CANCELLED','DENIED') then n:='Motivo registrado no cadastro principal'; end if;
insert into public.transport_request_history(request_id,municipality_id,user_id,action,old_status,new_status,old_data,new_data,note) values(new.id,new.municipality_id,(select auth.uid()),a,case when tg_op='UPDATE' then old.status end,new.status,case when tg_op='UPDATE' then private.audit_snapshot_request(old) end,private.audit_snapshot_request(new),n); return new; end $$;

create or replace function private.record_trip_history() returns trigger language plpgsql security definer set search_path='' as $$
declare a text;n text; begin if tg_op='INSERT' then a:='CREATED'; elsif new.status is distinct from old.status then a:='STATUS_CHANGED'; else a:='UPDATED'; end if; if new.status='CANCELLED' then n:='Motivo registrado no cadastro principal'; end if;
insert into public.trip_history(trip_id,municipality_id,user_id,action,old_status,new_status,old_data,new_data,note) values(new.id,new.municipality_id,(select auth.uid()),a,case when tg_op='UPDATE' then old.status end,new.status,case when tg_op='UPDATE' then private.audit_snapshot_trip(old) end,private.audit_snapshot_trip(new),n); return new; end $$;

create or replace function private.record_occurrence_history() returns trigger language plpgsql security definer set search_path='' as $$
declare a text; begin if tg_op='INSERT' then a:='CREATED'; elsif new.status is distinct from old.status then a:='STATUS_CHANGED'; else a:='UPDATED'; end if;
insert into public.occurrence_history(occurrence_id,municipality_id,user_id,action,old_status,new_status,old_data,new_data) values(new.id,new.municipality_id,(select auth.uid()),a,case when tg_op='UPDATE' then old.status end,new.status,case when tg_op='UPDATE' then private.audit_snapshot_occurrence(old) end,private.audit_snapshot_occurrence(new)); return new; end $$;