create table if not exists public.patient_import_batches (
 id uuid primary key default gen_random_uuid(), municipality_id uuid not null references public.municipalities(id), created_by uuid references public.profiles(id), file_name text not null,
 source text not null default 'FILE' check(source in ('FILE','ESUS','PEC','CADSUS','OTHER')), total_rows integer not null default 0, imported_rows integer not null default 0,
 duplicate_rows integer not null default 0, error_rows integer not null default 0, status text not null default 'PREVIEW' check(status in ('PREVIEW','COMPLETED','FAILED')),
 created_at timestamptz not null default now(), completed_at timestamptz);
alter table public.patient_import_batches enable row level security;
create policy patient_import_batches_select on public.patient_import_batches for select to authenticated using ((select private.current_user_role())='ADMIN'::public.user_role or municipality_id=(select private.current_user_municipality_id()));
create policy patient_import_batches_insert on public.patient_import_batches for insert to authenticated with check ((select private.current_user_role())='ADMIN'::public.user_role or (municipality_id=(select private.current_user_municipality_id()) and (select private.current_user_role())=any(array['GESTOR'::public.user_role,'OPERADOR'::public.user_role])));
create policy patient_import_batches_update on public.patient_import_batches for update to authenticated using ((select private.current_user_role())='ADMIN'::public.user_role or municipality_id=(select private.current_user_municipality_id())) with check ((select private.current_user_role())='ADMIN'::public.user_role or municipality_id=(select private.current_user_municipality_id()));
create index patient_import_batches_municipality_created_idx on public.patient_import_batches(municipality_id,created_at desc);
create table if not exists public.patient_external_links (id uuid primary key default gen_random_uuid(),municipality_id uuid not null references public.municipalities(id),patient_id uuid not null references public.patients(id) on delete cascade,source text not null,external_id text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(municipality_id,source,external_id));
alter table public.patient_external_links enable row level security;
create policy patient_external_links_select on public.patient_external_links for select to authenticated using ((select private.current_user_role())='ADMIN'::public.user_role or municipality_id=(select private.current_user_municipality_id()));
create policy patient_external_links_manage on public.patient_external_links for all to authenticated using ((select private.current_user_role())='ADMIN'::public.user_role or (municipality_id=(select private.current_user_municipality_id()) and (select private.current_user_role())=any(array['GESTOR'::public.user_role,'OPERADOR'::public.user_role]))) with check ((select private.current_user_role())='ADMIN'::public.user_role or (municipality_id=(select private.current_user_municipality_id()) and (select private.current_user_role())=any(array['GESTOR'::public.user_role,'OPERADOR'::public.user_role])));
create index patient_external_links_patient_idx on public.patient_external_links(patient_id);